/*global $*/
$("#aboutmePage").hide();
$("#portfolioPage").hide();
$("#contactsPage").hide();

$(".aboutMe").click(function(){
    $("#aboutmePage").show();
    $("#portfolioPage").hide();
    $("#contactsPage").hide();
    $("#homePage").hide();
});
$(".portfolio").click(function(){
    $("#aboutmePage").hide();
    $("#portfolioPage").show();
    $("#contactsPage").hide();
    $("#homePage").hide();
});
$(".contact").click(function(){
    $("#aboutmePage").hide();
    $("#portfolioPage").hide();
    $("#contactsPage").show();
    $("#homePage").hide();
});
$(".tony").click(function(){
    $("#aboutmePage").hide();
    $("#portfolioPage").hide();
    $("#contactsPage").hide();
    $("#homePage").show();
});